cluster:
  name: in-cluster
  url: ""
  rancher:
    id: c-XXXX

openstack:
  project: bbXX
  auth_url: "https://radiant.ncsa.illinois.edu:5000"
  credential_id: ""
  credential_secret: ""

notifications: {}
#  notifications.argoproj.io/subscribe.slack: my-channel

sync: false

healthmonitor:
  enabled: false
  targetRevision: HEAD
  nfs: false
  notifiers:
    console:
      report: change
      threshold: 0

ingresscontroller:
  enabled: false
  publicIP: 1.1.1.1
  #privateIP: 1.1.1.2
  #acme:
  #  email: devops.isda@lists.illinois.edu
  traefik1:
    version: "1.*"
  traefik2:
    version: "10.*"

metallb:
  enabled: false
  version: "0.10.*"
  addresses: []

# ----------------------------------------------------------------------
# STORAGE
# ----------------------------------------------------------------------

nfs:
  enabled: false
  version: "4.*"
  server: radiant-nfs.ncsa.illinois.edu
  path: /export
  pathPattern:

longhorn:
  enabled: false
  version: "1.*"
  replicas: 3

cinder:
  enabled: false
  version: "1.*"
