{{- if and .Values.ingresscontroller.enabled (eq .Values.ingresscontroller.class "traefik1") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster.name }}-traefik
  labels:
    cluster: {{ .Values.cluster.name | quote }}
    app: traefik
  namespace: argocd
  annotations:
    {{- toYaml .Values.notifications | nindent 4 }}
spec:
  project: {{ .Values.cluster.name }}
  destination:
    server: {{ .Values.cluster.url }}
    namespace: traefik
  syncPolicy:
    {{- if .Values.sync }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    {{- end }}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.helm.sh/stable
    chart: traefik
    targetRevision: {{ .Values.ingresscontroller.traefik1.version | quote }}
    helm:
      version: v3
      releaseName: traefik
      values: |
        loadBalancerIP: {{ .Values.ingresscontroller.privateIP | default .Values.ingresscontroller.publicIP }}
        externalIP: {{ .Values.ingresscontroller.publicIP }}
        externalTrafficPolicy: Local
        kubernetes:
          ingressEndpoint:
            ip: {{ .Values.ingresscontroller.publicIP }}
        rbac:
          enabled: true
        dashboard:
          enabled: {{ .Values.ingresscontroller.dashboard }}
          domain: traefik.{{ .Values.ingresscontroller.publicIP }}.xip.io
          ingress:
            annotations:
        acme:
          enabled: {{ .Values.ingresscontroller.acme }}
          {{- if .Values.ingresscontroller.acme }}
          challengeType: http-01
          email: {{ .Values.ingresscontroller.acme.email }}
          staging: {{ .Values.ingresscontroller.acme.staging }}
          logging: true
          persistence:
            enabled: true
          {{- end }}
        ssl:
          enabled: true
          enforced: true
          insecureSkipVerify: true
          tlsMinVersion: VersionTLS12
          cipherSuites:
            - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
            - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
            - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
            - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
{{- end }}
