notifiers:
  console:
    report: change
    threshold: 0
  # slack:
  # email:

nfs:
  enabled: false
  storageClass: nfs-condo

checks:
  ping:
    google:
      host: 8.8.8.8
      sleep: 10
  # hostport:
  # filewrite:


# name of existing secret, can contain the following keys:
# - notifiers: list of notifiers
# - checks: list of checks
# - config: dict with notifiers and checks
# existingSecret: 

image:
  pullPolicy: IfNotPresent
