apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-notifications
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.slack: sd-argocd
spec:
  project: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
      automated:
        prune: false
        selfHeal: false
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-notifications
    targetRevision: "1.*"
    helm:
      version: v3
      releaseName: argocd-notifications
      values: |
