{{ if .Values.raw.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster.name }}-raw
  labels:
    cluster: {{ .Values.cluster.name | quote }}
    app: metallb
  namespace: argocd
  annotations:
    {{- toYaml .Values.notifications | nindent 4 }}
spec:
  project: {{ .Values.cluster.name }}
  destination:
    server: {{ .Values.cluster.url }}
    namespace: default
  syncPolicy:
    {{- if .Values.sync }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    {{- end }}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://bedag.github.io/helm-charts/
    chart: raw
    targetRevision: {{ .Values.raw.version | quote }}
    helm:
      version: v3
      releaseName: raw
      values:
        values:
          {{ .Values.raw.values | nindent 10 }}
          {{ if .Values.metallb.enabled }}
          - |
              apiVersion: metallb.io/v1beta1
              kind: IPAddressPool
              metadata:
              name: terraform
              namespace: metallb-system
              spec:
              addresses:
                  {{- toYaml .Values.metallb.addresses | nindent 16 }}
          - |
              apiVersion: metallb.io/v1beta1
              kind: L2Advertisement
              metadata:
              name: l2advertisement1
              namespace: metallb-system
              spec:
              ipAddressPools:
                  - terraform
          {{- end }}
        templates:
          {{ .Values.raw.templates | nindent 10 }}
{{- end }}
