apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: healthmonitor
stringData:
  config.yml: |
    notifiers:
      {{- toYaml .Values.notifiers | nindent 6 }}
    checks:
      {{- if or .Values.checks.filewrite .Values.nfs.enabled }}
      filewrite:
        {{- with .Values.checks.filewrite }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.nfs }}
        nfs:
          file: /var/nfs/healthmonitor
        {{- end }}
      {{- end }}
      {{- if or .Values.checks.ping .Values.nfs.enabled }}
      ping:
        {{- with .Values.checks.ping }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.nfs.enabled }}
        nfs-server-1:
          host: 141.142.175.111
          sleep: 10
        nfs-server-2:
          host: 141.142.175.112
          sleep: 10
        nfs-server-3:
          host: 141.142.175.113
          sleep: 10
        nfs-server-4:
          host: 141.142.175.114
          sleep: 10
        nfs-server-5:
          host: 141.142.175.115
          sleep: 10
        nfs-server-6:
          host: 141.142.175.116
          sleep: 10
        nfs-server-7:
          host: 141.142.175.117
          sleep: 10
        nfs-server-8:
          host: 141.142.175.118
          sleep: 10
        {{- end }}
      {{- end }}
