apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: healthmonitor
stringData:
  config.yml: |
    notifiers:
      {{- toYaml .Values.notifiers | nindent 6 }}
    checks:
      {{- if or .Values.checks.filewrite .Values.nfs.enabled }}
      filewrite:
        {{- with .Values.checks.filewrite }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.nfs }}
        nfs:
          file: /var/nfs/healthmonitor
        {{- end }}
      {{- end }}
      {{- if or .Values.checks.ping .Values.nfs.enabled }}
      ping:
        {{- with .Values.checks.ping }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.nfs.enabled }}
        taiga-server-34:
          host: 141.142.224.34
          sleep: 10
        taiga-server-35:
          host: 141.142.224.35
          sleep: 10
        taiga-server-36:
          host: 141.142.224.36
          sleep: 10
        taiga-server-37:
          host: 141.142.224.37
          sleep: 10
        {{- end }}
      {{- end }}
